services:
  postgres-server:
    container_name: pg-server
    image: docker.io/library/postgres:17.6
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
volumes:
  postgres-data:

secrets:
  pg_password:
    file: pg_password.txt
